In [3]:
import glob
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

df= pd.read_csv('kidney_disease1.csv')
print(df.head())

      sg  al   sc  hemo  pcv  htn classification
0  1.020   1  1.2  15.4   44  yes            ckd
1  1.020   4  0.8  11.3   38   no            ckd
2  1.010   2  1.8   9.6   31   no            ckd
3  1.005   4  3.8  11.2   32  yes            ckd
4  1.010   2  1.4  11.6   35   no            ckd


In [15]:
df.dropna(axis=0,inplace=True)

In [16]:
df.reset_index(drop=True,inplace=True)

In [ ]:
#Splitting the data into independent and dependent variables
#Denoting the indepedent dataset as X and dependent dataset as Y

In [7]:
X= df.iloc[:,:6]
Y= df['classification']
print(X.head())
print(Y.head())

      sg  al   sc  hemo  pcv  htn
0  1.020   1  1.2  15.4   44  yes
1  1.020   4  0.8  11.3   38   no
2  1.010   2  1.8   9.6   31   no
3  1.005   4  3.8  11.2   32  yes
4  1.010   2  1.4  11.6   35   no
0    ckd
1    ckd
2    ckd
3    ckd
4    ckd
Name: classification, dtype: object


In [37]:
df.corr()

sg        al        sc      hemo       pcv
sg    1.000000 -0.513422 -0.401729  0.619735  0.597271
al   -0.513422  1.000000  0.505523 -0.655087 -0.621687
sc   -0.401729  0.505523  1.000000 -0.586453 -0.583498
hemo  0.619735 -0.655087 -0.586453  1.000000  0.886355
pcv   0.597271 -0.621687 -0.583498  0.886355  1.000000

In [ ]:
import sklearn

In [33]:
from sklearn.preprocessing import LabelEncoder

In [35]:
lb=LabelEncoder()
y=lb.fit_transform(Y)

In [42]:
#Transform the non-numeric data in the columns
lb= LabelEncoder()
for col in df.columns:
    if(df[col].dtype==np.number):
        continue
    else:
        df[col]= lb.fit_transform(df[col])
df

sg  al   sc  hemo  pcv  htn  classification
0    1.020   1  1.2  15.4   28    1               0
1    1.020   4  0.8  11.3   22    0               0
2    1.010   2  1.8   9.6   15    0               0
3    1.005   4  3.8  11.2   16    1               0
4    1.010   2  1.4  11.6   19    0               0
..     ...  ..  ...   ...  ...  ...             ...
282  1.020   0  0.5  15.7   31    0               1
283  1.025   0  1.2  16.5   38    0               1
284  1.020   0  0.6  15.8   33    0               1
285  1.025   0  1.0  14.2   35    0               1
286  1.025   0  1.1  15.8   37    0               1

[287 rows x 7 columns]

In [56]:
X= df.iloc[:,:6].values
Y= df['classification'].values

In [57]:
#Splitting the data into training and testing data

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [60]:
type(x_train)

numpy.ndarray

In [61]:
x_train.shape

(229, 6)

In [62]:
y_train.shape

(229,)

In [63]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [64]:
pipe=Pipeline([
    ('rescale',StandardScaler()),
    ('classifier',LogisticRegression())
])

In [65]:
x_train

array([[ 1.01 ,  1.   ,  1.1  , 15.   , 32.   ,  0.   ],
       [ 1.02 ,  0.   ,  1.2  , 16.2  , 34.   ,  0.   ],
       [ 1.02 ,  0.   ,  1.2  , 15.7  , 28.   ,  0.   ],
       ...,
       [ 1.015,  3.   ,  3.3  , 11.3  , 15.   ,  1.   ],
       [ 1.01 ,  2.   ,  3.3  , 10.9  , 21.   ,  0.   ],
       [ 1.025,  0.   ,  0.9  , 13.9  , 32.   ,  0.   ]])

In [66]:
pipe.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('rescale',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('classifier',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [67]:
pipe.predict(x_test)

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0])

In [70]:
pipe.predict([[1.025,0,1.2,15.4,48,0]])

array([1])